# Generated by Django 3.1.3 on 2021-12-05 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='added',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 5, 16, 23, 27, 913748, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
