# Generated by Django 3.1.3 on 2021-12-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remainder_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='mail',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
