# Generated by Django 3.1.3 on 2022-02-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remainder_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='remainder',
            name='set_time',
            field=models.DateTimeField(null=True),
        ),
    ]
