# Generated by Django 3.1.3 on 2024-06-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_remainder_set_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remainder',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
